### ISSUE TITLE
How to get nested objects key?

### ISSUE THREAD

**Issue by ivellios** [MeilleursAgents/terraform-provider-ansiblevault#132]
How do I get the value in the nested objects? I tried the typical for yaml dot-notation, but it does not work. 

```hcl
data "ansiblevault_path" "my_key" {
  path = "./vault.yaml"
  key = "group.subgroup.my_key"
```

The vault file:
```yaml
group:
  subgroup:
    my_key: value
```

I get Error that it is not found in the vault.
